import sys
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QMainWindow, QLineEdit, QPushButton, QLabel

class Application(QMainWindow):
    def __init__(self):
        super().__init__()
        self.title = "KANBAN BOARD"
        self.left = 300
        self.top = 100
        self.width = 1401
        self.height = 872
        self.main_scr()
        self.show()

    def main_scr(self):
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)
        self.setWindowIcon(QIcon(r"C:\Users\user\AppData\Local\Programs\Microsoft VS Code\tools\icon.jpg"))
        self.setStyleSheet("background-image : url(maincolumns.jpg); ")

        self.add1todo = QPushButton(self)
        self.add1todo.setGeometry(100, 145, 100, 30)
        self.add1todo.setText("+ Add a task")
        self.add1todo.setStyleSheet("background-image: url(white.jpg);")
        self.add1todo.clicked.connect(self.addftodo)
        self.add1todo.show()

        self.add2todo = QPushButton(self)
        self.add2todo.setGeometry(100, 325, 100, 30)
        self.add2todo.setText("+ Add a task")
        self.add2todo.setStyleSheet("background-image: url(white.jpg);")
        self.add2todo.clicked.connect(self.addstodo)
        self.add2todo.show()

        self.add3todo = QPushButton(self)
        self.add3todo.setGeometry(100, 525, 100, 30)
        self.add3todo.setText("+ Add a task")
        self.add3todo.setStyleSheet("background-image: url(white.jpg);")
        self.add3todo.clicked.connect(self.addttodo)
        self.add3todo.show()

        self.add4todo = QPushButton(self)
        self.add4todo.setGeometry(100, 735, 100, 30)
        self.add4todo.setText("+ Add a task")
        self.add4todo.setStyleSheet("background-image: url(white.jpg);")
        self.add4todo.clicked.connect(self.addctodo)
        self.add4todo.show()

        self.add1prog = QPushButton(self)
        self.add1prog.setGeometry(470, 145, 100, 30)
        self.add1prog.setText("+ Add a task")
        self.add1prog.setStyleSheet("background-image: url(white.jpg);")
        self.add1prog.clicked.connect(self.addfprog)
        self.add1prog.show()

        self.add2prog = QPushButton(self)
        self.add2prog.setGeometry(470, 325, 100, 30)
        self.add2prog.setText("+ Add a task")
        self.add2prog.setStyleSheet("background-image: url(white.jpg);")
        self.add2prog.clicked.connect(self.addsprog)
        self.add2prog.show()

        self.add3prog = QPushButton(self)
        self.add3prog.setGeometry(470, 525, 100, 30)
        self.add3prog.setText("+ Add a task")
        self.add3prog.setStyleSheet("background-image: url(white.jpg);")
        self.add3prog.clicked.connect(self.addtprog)
        self.add3prog.show()

        self.add4prog = QPushButton(self)
        self.add4prog.setGeometry(470, 735, 100, 30)
        self.add4prog.setText("+ Add a task")
        self.add4prog.setStyleSheet("background-image: url(white.jpg);")
        self.add4prog.clicked.connect(self.addcprog)
        self.add4prog.show()

        self.add1test = QPushButton(self)
        self.add1test.setGeometry(825, 145, 100, 30)
        self.add1test.setText("+ Add a task")
        self.add1test.setStyleSheet("background-image: url(white.jpg);")
        self.add1test.clicked.connect(self.addftest)
        self.add1test.show()

        self.add2test = QPushButton(self)
        self.add2test.setGeometry(825, 320, 100, 30)
        self.add2test.setText("+ Add a task")
        self.add2test.setStyleSheet("background-image: url(white.jpg);")
        self.add2test.clicked.connect(self.addstest)
        self.add2test.show()

        self.add3test = QPushButton(self)
        self.add3test.setGeometry(825, 525, 100, 30)
        self.add3test.setText("+ Add a task")
        self.add3test.setStyleSheet("background-image: url(white.jpg);")
        self.add3test.clicked.connect(self.addttest)
        self.add3test.show()

        self.add4test = QPushButton(self)
        self.add4test.setGeometry(825, 735, 100, 30)
        self.add4test.setText("+ Add a task")
        self.add4test.setStyleSheet("background-image: url(white.jpg);")
        self.add4test.clicked.connect(self.addctest)
        self.add4test.show()

        self.add1did = QPushButton(self)
        self.add1did.setGeometry(1180, 145, 100, 30)
        self.add1did.setText("+ Add a task")
        self.add1did.setStyleSheet("background-image: url(white.jpg);")
        self.add1did.clicked.connect(self.addfdid)
        self.add1did.show()

        self.add2did = QPushButton(self)
        self.add2did.setGeometry(1180, 320, 100, 30)
        self.add2did.setText("+ Add a task")
        self.add2did.setStyleSheet("background-image: url(white.jpg);")
        self.add2did.clicked.connect(self.addsdid)
        self.add2did.show()

        self.add3did = QPushButton(self)
        self.add3did.setGeometry(1180, 525, 100, 30)
        self.add3did.setText("+ Add a task")
        self.add3did.setStyleSheet("background-image: url(white.jpg);")
        self.add3did.clicked.connect(self.addtdid)
        self.add3did.show()

        self.add4did = QPushButton(self)
        self.add4did.setGeometry(1180, 730, 100, 30)
        self.add4did.setText("+ Add a task")
        self.add4did.setStyleSheet("background-image: url(white.jpg);")
        self.add4did.clicked.connect(self.addcdid)
        self.add4did.show()

    def addftodo(self):
        self.name1do = QLabel(self)
        self.name1do.setText("name: ")
        self.name1do.setGeometry(5, 80, 60, 30)
        self.name1do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.firstdo = QLineEdit(self)
        self.firstdo.setGeometry(80, 80, 249, 30)
        self.firstdo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")

        self.duty1do = QLabel(self)
        self.duty1do.setText("duty: ")
        self.duty1do.setGeometry(5, 145, 60, 30)
        self.duty1do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.seconddo = QLineEdit(self)
        self.seconddo.setGeometry(80, 145, 249, 30)
        self.seconddo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")

        self.deadline1do = QLabel(self)
        self.deadline1do.setText("finish: ")
        self.deadline1do.setGeometry(5, 210, 60, 30)
        self.deadline1do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.thirddo = QLineEdit(self)
        self.thirddo.setGeometry(80, 210, 249, 30)
        self.thirddo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.thirddo.show()
        self.seconddo.show()
        self.firstdo.show()
        self.name1do.show()
        self.duty1do.show()
        self.deadline1do.show()

    def addstodo(self):
        self.name2do = QLabel(self)
        self.name2do.setText("name: ")
        self.name2do.setGeometry(5, 260, 60, 30)
        self.name2do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.fourthdo = QLineEdit(self)
        self.fourthdo.setGeometry(80, 260, 249, 30)
        self.fourthdo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fourthdo.show()

        self.duty2do = QLabel(self)
        self.duty2do.setText("duty: ")
        self.duty2do.setGeometry(5, 325, 60, 30)
        self.duty2do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.fifthdo = QLineEdit(self)
        self.fifthdo.setGeometry(80, 325, 249, 30)
        self.fifthdo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fifthdo.show()

        self.deadline2do = QLabel(self)
        self.deadline2do.setText("finish: ")
        self.deadline2do.setGeometry(5, 390, 60, 30)
        self.deadline2do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.sixthdo = QLineEdit(self)
        self.sixthdo.setGeometry(80, 390, 249, 30)
        self.sixthdo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.sixthdo.show()
        self.name2do.show()
        self.duty2do.show()
        self.deadline2do.show()

    def addttodo(self):
        self.name3do = QLabel(self)
        self.name3do.setText("name: ")
        self.name3do.setGeometry(5, 465, 60, 30)
        self.name3do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.seventhdo = QLineEdit(self)
        self.seventhdo.setGeometry(83, 465, 245, 30)
        self.seventhdo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.seventhdo.show()

        self.duty3do = QLabel(self)
        self.duty3do.setText("duty: ")
        self.duty3do.setGeometry(5, 525, 60, 30)
        self.duty3do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.eightdo = QLineEdit(self)
        self.eightdo.setGeometry(83, 525, 245, 30)
        self.eightdo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.eightdo.show()

        self.deadline3do = QLabel(self)
        self.deadline3do.setText("finish: ")
        self.deadline3do.setGeometry(5, 590, 60, 30)
        self.deadline3do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.ninedo = QLineEdit(self)
        self.ninedo.setGeometry(83, 590, 245, 30)
        self.ninedo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.ninedo.show()
        self.name3do.show()
        self.duty3do.show()
        self.deadline3do.show()

    def addctodo(self):
        self.name4do = QLabel(self)
        self.name4do.setText("name: ")
        self.name4do.setGeometry(5, 670, 60, 30)
        self.name4do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.tendo = QLineEdit(self)
        self.tendo.setGeometry(83, 670, 245, 30)
        self.tendo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.tendo.show()

        self.duty4do = QLabel(self)
        self.duty4do.setText("duty: ")
        self.duty4do.setGeometry(5, 735, 60, 30)
        self.duty4do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.elevendo = QLineEdit(self)
        self.elevendo.setGeometry(83, 735, 245, 30)
        self.elevendo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.elevendo.show()

        self.deadline4do = QLabel(self)
        self.deadline4do.setText("finish: ")
        self.deadline4do.setGeometry(5, 800, 60, 30)
        self.deadline4do.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.twelvedo = QLineEdit(self)
        self.twelvedo.setGeometry(83, 800, 245, 30)
        self.twelvedo.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.twelvedo.show()
        self.name4do.show()
        self.duty4do.show()
        self.deadline4do.show()
    
    def addfprog(self):
        self.name1prog = QLabel(self)
        self.name1prog.setText("name: ")
        self.name1prog.setGeometry(350, 80, 60, 30)
        self.name1prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty1prog = QLabel(self)
        self.duty1prog.setText("duty: ")
        self.duty1prog.setGeometry(350, 145, 60, 30)
        self.duty1prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline1prog = QLabel(self)
        self.deadline1prog.setText("finish: ")
        self.deadline1prog.setGeometry(350, 210, 60, 30)
        self.deadline1prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.firstprog = QLineEdit(self)
        self.firstprog.setGeometry(420, 80, 275, 30)
        self.firstprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.firstprog.show()

        self.secondprog = QLineEdit(self)
        self.secondprog.setGeometry(420, 145, 275, 30)
        self.secondprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.secondprog.show()

        self.thirdprog = QLineEdit(self)
        self.thirdprog.setGeometry(420, 210, 275, 30)
        self.thirdprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.thirdprog.show()
        self.name1prog.show()
        self.duty1prog.show()
        self.deadline1prog.show()

    def addsprog(self):
        self.name2prog = QLabel(self)
        self.name2prog.setText("name: ")
        self.name2prog.setGeometry(350, 260, 60, 30)
        self.name2prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty2prog = QLabel(self)
        self.duty2prog.setText("duty: ")
        self.duty2prog.setGeometry(350, 325, 60, 30)
        self.duty2prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline2prog = QLabel(self)
        self.deadline2prog.setText("finish: ")
        self.deadline2prog.setGeometry(350, 390, 60, 30)
        self.deadline2prog.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.fourthprog = QLineEdit(self)
        self.fourthprog.setGeometry(420, 260, 275, 30)
        self.fourthprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fourthprog.show()

        self.fifthprog = QLineEdit(self)
        self.fifthprog.setGeometry(420, 325, 275, 30)
        self.fifthprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fifthprog.show()

        self.sixthprog = QLineEdit(self)
        self.sixthprog.setGeometry(420, 390, 275, 30)
        self.sixthprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.sixthprog.show()

        self.name2prog.show()
        self.duty2prog.show()
        self.deadline2prog.show()

    def addtprog(self):
        self.name3prog = QLabel(self)
        self.name3prog.setText("name: ")
        self.name3prog.setGeometry(350, 465, 60, 30)
        self.name3prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty3prog = QLabel(self)
        self.duty3prog.setText("duty: ")
        self.duty3prog.setGeometry(350, 525, 60, 30)
        self.duty3prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline3prog = QLabel(self)
        self.deadline3prog.setText("finish: ")
        self.deadline3prog.setGeometry(350, 590, 60, 30)
        self.deadline3prog.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.seventhprog = QLineEdit(self)
        self.seventhprog.setGeometry(420, 465, 275, 30)
        self.seventhprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.seventhprog.show()

        self.eightprog = QLineEdit(self)
        self.eightprog.setGeometry(420, 525, 275, 30)
        self.eightprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.eightprog.show()

        self.nineprog = QLineEdit(self)
        self.nineprog.setGeometry(420, 590, 275, 30)
        self.nineprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.nineprog.show()
        
        self.name3prog.show()
        self.duty3prog.show()
        self.deadline3prog.show()

    def addcprog(self):
        self.name4prog = QLabel(self)
        self.name4prog.setText("name: ")
        self.name4prog.setGeometry(350, 670, 60, 30)
        self.name4prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty4prog = QLabel(self)
        self.duty4prog.setText("duty: ")
        self.duty4prog.setGeometry(350, 735, 60, 30)
        self.duty4prog.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline4prog = QLabel(self)
        self.deadline4prog.setText("finish: ")
        self.deadline4prog.setGeometry(350, 800, 60, 30)
        self.deadline4prog.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.tenprog = QLineEdit(self)
        self.tenprog.setGeometry(420, 670, 275, 30)
        self.tenprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.tenprog.show()

        self.elevenprog = QLineEdit(self)
        self.elevenprog.setGeometry(420, 735, 275, 30)
        self.elevenprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.elevenprog.show()

        self.twelveprog = QLineEdit(self)
        self.twelveprog.setGeometry(420, 800, 275, 30)
        self.twelveprog.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.twelveprog.show()
        self.name4prog.show()
        self.duty4prog.show()
        self.deadline4prog.show()

    def addftest(self):
        self.name1test = QLabel(self)
        self.name1test.setText("name: ")
        self.name1test.setGeometry(725, 83, 60, 30)
        self.name1test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty1test = QLabel(self)
        self.duty1test.setText("duty: ")
        self.duty1test.setGeometry(725, 145, 60, 30)
        self.duty1test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline1test = QLabel(self)
        self.deadline1test.setText("finish: ")
        self.deadline1test.setGeometry(725, 210, 60, 30)
        self.deadline1test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        
        self.firsttest = QLineEdit(self)
        self.firsttest.setGeometry(795, 83, 250, 30)
        self.firsttest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.firsttest.show()

        self.secondtest = QLineEdit(self)
        self.secondtest.setGeometry(795, 145, 250, 30)
        self.secondtest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.secondtest.show()

        self.thirdtest = QLineEdit(self)
        self.thirdtest.setGeometry(795, 210, 250, 30)
        self.thirdtest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.thirdtest.show()
        self.name1test.show()
        self.duty1test.show()
        self.deadline1test.show()

    def addstest(self):
        self.name2test = QLabel(self)
        self.name2test.setText("name: ")
        self.name2test.setGeometry(725, 258, 60, 30)
        self.name2test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty2test = QLabel(self)
        self.duty2test.setText("duty: ")
        self.duty2test.setGeometry(725, 320, 60, 30)
        self.duty2test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline2test = QLabel(self)
        self.deadline2test.setText("finish: ")
        self.deadline2test.setGeometry(725, 385, 60, 30)
        self.deadline2test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        
        self.fourthtest = QLineEdit(self)
        self.fourthtest.setGeometry(795, 258, 250, 30)
        self.fourthtest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fourthtest.show()

        self.fifthtest = QLineEdit(self)
        self.fifthtest.setGeometry(795, 320, 250, 30)
        self.fifthtest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fifthtest.show()

        self.sixthtest = QLineEdit(self)
        self.sixthtest.setGeometry(795, 385, 250, 30)
        self.sixthtest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.sixthtest.show()

        self.name2test.show()
        self.duty2test.show()
        self.deadline2test.show()

    def addttest(self):
        self.name3test = QLabel(self)
        self.name3test.setText("name: ")
        self.name3test.setGeometry(725, 465, 60, 30)
        self.name3test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty3test = QLabel(self)
        self.duty3test.setText("duty: ")
        self.duty3test.setGeometry(725, 525, 60, 30)
        self.duty3test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline3test = QLabel(self)
        self.deadline3test.setText("finish: ")
        self.deadline3test.setGeometry(725, 590, 60, 30)
        self.deadline3test.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.seventhtest = QLineEdit(self)
        self.seventhtest.setGeometry(795, 465, 250, 30)
        self.seventhtest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.seventhtest.show()

        self.eighttest = QLineEdit(self)
        self.eighttest.setGeometry(795, 525, 250, 30)
        self.eighttest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.eighttest.show()

        self.ninetest = QLineEdit(self)
        self.ninetest.setGeometry(795, 590, 250, 30)
        self.ninetest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.ninetest.show()

        self.name3test.show()
        self.duty3test.show()
        self.deadline3test.show()

    def addctest(self):
        self.name4test = QLabel(self)
        self.name4test.setText("name: ")
        self.name4test.setGeometry(725, 670, 60, 30)
        self.name4test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty4test = QLabel(self)
        self.duty4test.setText("duty: ")
        self.duty4test.setGeometry(725, 735, 60, 30)
        self.duty4test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline4test = QLabel(self)
        self.deadline4test.setText("finish: ")
        self.deadline4test.setGeometry(725, 800, 60, 30)
        self.deadline4test.setStyleSheet("font-size: 22px; color: mediumblue; ")
        
        self.tentest = QLineEdit(self)
        self.tentest.setGeometry(795, 670, 250, 30)
        self.tentest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.tentest.show()

        self.eleventest = QLineEdit(self)
        self.eleventest.setGeometry(795, 735, 250, 30)
        self.eleventest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.eleventest.show()

        self.twelvetest = QLineEdit(self)
        self.twelvetest.setGeometry(795, 800, 250, 30)
        self.twelvetest.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.twelvetest.show()

        self.name4test.show()
        self.duty4test.show()
        self.deadline4test.show()

    def addfdid(self):
        self.name1did = QLabel(self)
        self.name1did.setText("name: ")
        self.name1did.setGeometry(1060, 83, 60, 30)
        self.name1did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty1did = QLabel(self)
        self.duty1did.setText("duty: ")
        self.duty1did.setGeometry(1060, 145, 60, 30)
        self.duty1did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline1did = QLabel(self)
        self.deadline1did.setText("finish: ")
        self.deadline1did.setGeometry(1060, 210, 60, 30)
        self.deadline1did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        
        self.firstdid = QLineEdit(self)
        self.firstdid.setGeometry(1140, 83, 260, 30)
        self.firstdid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.firstdid.show()

        self.seconddid = QLineEdit(self)
        self.seconddid.setGeometry(1140, 145, 260, 30)
        self.seconddid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.seconddid.show()

        self.thirddid = QLineEdit(self)
        self.thirddid.setGeometry(1140, 210, 260, 30)
        self.thirddid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.thirddid.show()

        self.name1did.show()
        self.duty1did.show()
        self.deadline1did.show()

    def addsdid(self):
        self.name2did = QLabel(self)
        self.name2did.setText("name: ")
        self.name2did.setGeometry(1060, 255, 60, 30)
        self.name2did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty2did = QLabel(self)
        self.duty2did.setText("duty: ")
        self.duty2did.setGeometry(1060, 320, 60, 30)
        self.duty2did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline2did = QLabel(self)
        self.deadline2did.setText("finish: ")
        self.deadline2did.setGeometry(1060, 385, 60, 30)
        self.deadline2did.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.fourthdid = QLineEdit(self)
        self.fourthdid.setGeometry(1140, 255, 260, 30)
        self.fourthdid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fourthdid.show()

        self.fifthdid = QLineEdit(self)
        self.fifthdid.setGeometry(1140, 320, 260, 30)
        self.fifthdid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.fifthdid.show()

        self.sixthdid = QLineEdit(self)
        self.sixthdid.setGeometry(1140, 385, 260, 30)
        self.sixthdid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.sixthdid.show()
        self.name2did.show()
        self.duty2did.show()
        self.deadline2did.show()

    def addtdid(self):
        self.name3did = QLabel(self)
        self.name3did.setText("name: ")
        self.name3did.setGeometry(1060, 465, 60, 30)
        self.name3did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty3did = QLabel(self)
        self.duty3did.setText("duty: ")
        self.duty3did.setGeometry(1060, 525, 60, 30)
        self.duty3did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline3did = QLabel(self)
        self.deadline3did.setText("finish: ")
        self.deadline3did.setGeometry(1060, 590, 60, 30)
        self.deadline3did.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.seventhdid = QLineEdit(self)
        self.seventhdid.setGeometry(1140, 465, 260, 30)
        self.seventhdid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.seventhdid.show()

        self.eightdid = QLineEdit(self)
        self.eightdid.setGeometry(1140, 525, 260, 30)
        self.eightdid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.eightdid.show()

        self.ninedid = QLineEdit(self)
        self.ninedid.setGeometry(1140, 590, 260, 30)
        self.ninedid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.ninedid.show()
        self.name3did.show()
        self.duty3did.show()
        self.deadline3did.show()

    def addcdid(self):
        self.name4did = QLabel(self)
        self.name4did.setText("name: ")
        self.name4did.setGeometry(1060, 668, 60, 30)
        self.name4did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.duty4did = QLabel(self)
        self.duty4did.setText("duty: ")
        self.duty4did.setGeometry(1060, 730, 60, 30)
        self.duty4did.setStyleSheet("font-size: 22px; color: mediumblue; ")
        self.deadline4did = QLabel(self)
        self.deadline4did.setText("finish: ")
        self.deadline4did.setGeometry(1060, 795, 60, 30)
        self.deadline4did.setStyleSheet("font-size: 22px; color: mediumblue; ")

        self.tendid = QLineEdit(self)
        self.tendid.setGeometry(1140, 668, 260, 30)
        self.tendid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.tendid.show()

        self.elevendid = QLineEdit(self)
        self.elevendid.setGeometry(1140, 730, 260, 30)
        self.elevendid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.elevendid.show()

        self.twelvedid = QLineEdit(self)
        self.twelvedid.setGeometry(1140, 795, 260, 30)
        self.twelvedid.setStyleSheet("background-image: url(white.jpg); font-size: 20px; ")
        self.twelvedid.show()
        self.show()
        self.name4did.show()
        self.duty4did.show()
        self.deadline4did.show()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    start = Application()
    sys.exit(app.exec_())
